name: ci

on:
  push:
    branches: [ "dev", "master", "releases/v*" ]
  pull_request:
    branches: [ "dev", "master", "releases/v*" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet --version
    - name: Build
      run: dotnet --version
    - name: Test
      run: dotnet --version

